# Generated by Django 4.1.2 on 2022-10-30 08:30

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('note', '0001_initial'),
    ]

    operations = [
        migrations.RenameModel(
            old_name='NoteModel',
            new_name='Note',
        ),
    ]
